- package-lock.json
- package.json
- src/App.svelte
- src/Router.svelte
- src/pages/List.svelte
- src/pages/Login.svelte
- src/pages/Register.svelte
(이슈링크 혹은 참조링크)
https://teamtuesday.atlassian.net/browse/SISO-49
Router(tinro)적용 및 라우터를 사용하기 위한 기본 세팅 (pages에 몇개의 파일 추가)
Router가 잘 동작하는지 테스트
6/11
> Router(tinro)적용 및 기본 세팅

- public/index.html
- public/minireset.css
(이슈링크 혹은 참조링크)
https://teamtuesday.atlassian.net/browse/SISO-64
reset.css중 minireset.css적용
reset css의 종류가 다양한데, 그 중에서 가장 심플해 보이는 최소한의 reset을 적용하기로 임의로 결정함.
추후 다른 의견이 있으면 간단히 변경할 수 있으므로, 일단 적용하기로.
reset.css에 대한 조사
reset css에 대한 다른 의견이 있다면 반영
6/13
> Feat: [SISO-64] reset.css 적용

- package-lock.json
- package.json
- rollup.config.js
- svelte.config.js
(이슈링크 혹은 참조링크)
https://teamtuesday.atlassian.net/browse/SISO-65
브라우저 밴더 접두사를 추가하기 위한 autoprefixer 적용
동작하는지 테스트
6/20
> Feat: [SISO-65] autoprefixer 적용

- .github/CODEOWNERS
(이슈링크 혹은 참조링크)
https://teamtuesday.atlassian.net/browse/SISO-67
리뷰어 지정이 codeowners로 동작하도록 설정
team (siso-frontend)을 생성하고,해당 team 설정으로 리뷰어가 2명 랜덤으로 지정되도록 설정
리뷰어의 수가 본인제외 1명이면 충분하지 않을지? 2명도 많지 않나 싶었음.
리뷰를 더 독려할 수 있는 방법이 있을지.
Merge전은 아니지만, Merge후에 리뷰어 랜덤지정이 잘 되는지 테스트 필요
6/20
> Feat: [SISO-67] codeowners 적용

- .eslintrc.js
- package-lock.json
- package.json
- rollup.config.js
- src/App.svelte
(이슈링크 혹은 참조링크)
https://teamtuesday.atlassian.net/browse/SISO-57
eslint 적용
설정값을 특별히 추가하지 않았는데, airbnb나 google같은 가이드를 따라가도록 설정해야하는건 아닐지? 혹은 특히 설정해야 하는게 있는데 누락된건 아닌지 (추후에 추가해도 괜찮을 부분인거 같음)
npm run lint를 통해 동작하는지 테스트
6/20
> Feat: [SISO-57] eslint 적용

- .prettierignore
- .prettierrc
- package-lock.json
- package.json
- public/global.css
- public/index.html
- public/minireset.css
- src/App.svelte
- src/Router.svelte
- src/pages/List.svelte
- src/pages/Login.svelte
- src/pages/Register.svelte
(이슈링크 혹은 참조링크)
https://teamtuesday.atlassian.net/browse/SISO-48
prettier 적용
적용 잘 되는지 테스트
prettierrc 설정값에 대한 논의 필요. 추후 수정 가능.
6/20
> Feat: [SISO-48] prettier 추가

- .babelrc
- .eslintcache
- package-lock.json
- package.json
- src/__tests__/button.test.ts
- src/components/Button.svelte
- src/global.d.ts
- src/pages/List.svelte
- tsconfig.json
(이슈링크 혹은 참조링크)
https://teamtuesday.atlassian.net/browse/SISO-70
https://teamtuesday.atlassian.net/wiki/spaces/TEAMTUESDA/pages/25755649/20220628+-+Svelte
- test code에 필요한 패키지 설치
- 테스트를 위한 Button component 추가
- Button component에 대한 테스트 케이스 작성
- @testing-library/svelte에 render 인자 타입이 SvelteComponent이기 떄문에
global.d.ts파일의 export타입을 SvelteComponent로 변경했습니다
- npm run test(혹은 npm run test:watch)로 테스트 실행
> Test: [SISO-70] 테스트 코드 적용

- package-lock.json
- package.json
- src/service/api.ts
(이슈링크 혹은 참조링크)
https://teamtuesday.atlassian.net/browse/SISO-76
api통신을 위한 axios 기본 설정 추가
response의 data의 타입을 any로 설정해두었는데, any를 배제할 수 있는 방법이 있을지..
통신이 정상적으로 되는지 확인함.
7/24
> Feat: [SISO-78] axios 설정 추가

- src/pages/List.svelte
- src/store.ts
(이슈링크 혹은 참조링크)
https://teamtuesday.atlassian.net/browse/SISO-77
store기본 설정 및 vote불러오는 로직 수정
store의 사용범위
store로 변경 후에도 데이터를 잘 가져오는지 확인
8/2
> Feat: [SISO-77] store기본 설정

- src/App.svelte
(이슈링크 혹은 참조링크)
- `@/router.svelte` -> `@/Router.svelte`
- 빌드 시 에러가 발생하여 수정합니다.
> fix: [NO-ISSUE] Router.svelte 파일 대소문자 수정

- src/components/Vote/Vote.svelte
- src/components/Vote/VoteContents.svelte
- src/pages/List.svelte
- src/service/api.ts
- src/store.ts
- src/store/voteStore.ts
- src/store/voteSubjectStore.ts
- types/index.d.ts
https://teamtuesday.atlassian.net/browse/SISO-93
(이슈링크 혹은 참조링크)
투표하기 api 적용
API정상동작 확인
투표한 후에 동작에 대한 구현필요 (R2)
1/3
> 투표하기 api 적용

- package.json
- src/components/Vote/VoteContents.svelte
- src/components/common/Button.svelte
- src/components/common/confirm/Confirm.svelte
- src/components/modal/Modal.svelte
- src/pages/Home.svelte
- src/utils/UI.ts
[https://teamtuesday.atlassian.net/browse/SISO-126](https://teamtuesday.atlassian.net/browse/SISO-126)
npm check 시 오류 수정
Svelte Component를 parameter로 넘겼을 때 여러가지 type을 시도해보아도 오류가 나와 any로 처리...
컴포넌트 type을 any가 아닌 컴포넌트에 맞는 type이 무엇이 있는지 고민... (검색만 1시간 해봄)
1/24(화)
> Feat: [SISO-126] npm check 시 오류 수정

- src/components/Vote/Vote.svelte
https://teamtuesday.atlassian.net/browse/SISO-129
(이슈링크 혹은 참조링크)
npm run check 실행시 발생하는 router.parms관련 오류 수정
ASAP
> npm run check시 발생하는 router.params오류 수정

- package.json
(이슈링크 혹은 참조링크)
https://teamtuesday.atlassian.net/browse/SISO-112?atlOrigin=eyJpIjoiYzlhMzEwMTk0ZDc2NDdmOGIzZmYzYzdkMjlkYWY5ZTIiLCJwIjoiaiJ9
- host 옵션 추가해서 Network추가
ASAP
> Feat: [SISO-112] 프론트 host 옵션 추가

- package-lock.json
- package.json
- rollup.config.js
- src/service/api.ts
https://teamtuesday.atlassian.net/browse/SISO-128
(이슈링크 혹은 참조링크)
dotenv추가 및 env를 통한 baseURL설정
1. 각 환경별로 env에 있는 BASE_URL의 값을 바꾸는게 아니라, env파일자체를 각 환경에 맞게 불러오게끔 하고 싶었으나, 방법을 찾지 못했음. (전자의 방법으로도 구동에는 문제가 없을것 같아서 일단 진행)
2. String(JSON.parse('__myapp').env.BASE_URL); 처럼 지저분하게가 아니라 그냥 깔끔하게 ___myapp.env.BASE_URL이라고 해서 가져오고싶었으나,, 해결하지 못함.
구동확인
1/31
> dotenv 추가 및 baseURL설정

- src/components/Vote/VoteContents.svelte
- src/store/voteStore.ts
- src/store/voteSubjectStore.ts
- types/index.d.ts
https://teamtuesday.atlassian.net/browse/SISO-111
(이슈링크 혹은 참조링크)
투표 후 결과 출력되도록
동작확인.
애니메이션 추가. (숫자증가 및 bar 확대 애니메이션)
현 사용자가 투표를 어디에 했는지 받아와서 투표페이지 진입시 투표헀다면 결과가 바로 나오도록 추가 처리 필요함.
02/14
> 결과보여주기 (애니메이션 추가 전)

- .eslintrc.cjs
- package-lock.json
- package.json
- src/Router.svelte
- src/pages/Login.svelte
- src/pages/Register.svelte
- src/pages/auth/Login.svelte
- src/pages/auth/Register.svelte
- src/utils/Auth.ts
- tsconfig.json
- types/auth.d.ts
[https://teamtuesday.atlassian.net/browse/SISO-125](https://teamtuesday.atlassian.net/browse/SISO-125)
로그인, 회원가입 임시 페이지 추가
2 / 7(화)
> Feat: [SISO-125] 로그인, 회원가입 임시 페이지 추가

- package-lock.json
- package.json
- src/components/Vote/Vote.svelte
- src/components/Vote/VoteContents.svelte
https://teamtuesday.atlassian.net/browse/SISO-111
(이슈링크 혹은 참조링크)
카운트업 라이브러리 추가
progress bar 애니메이션 추가
asap
> count-up 추가

- package-lock.json
- src/components/Vote/VoteContents.svelte
- src/main.ts
- types/svelte-countup.d.ts
https://teamtuesday.atlassian.net/browse/SISO-111
(이슈링크 혹은 참조링크)
> build에러 해결

- package-lock.json
- package.json
- src/__tests__/auth/__snapshots__/mypage.test.ts.snap
- src/__tests__/auth/mypage.test.ts
- src/main.ts
- src/utils/Auth.ts
- tsconfig.json
[https://teamtuesday.atlassian.net/browse/SISO-136](https://teamtuesday.atlassian.net/browse/SISO-136)
npm run check 시 오류 수정 및 mypage 테스트 코드 추가
> npm run check 시 오류 수정 및 mypage 테스트 코드 추가

- package-lock.json
- package.json
- src/__tests__/auth/__snapshots__/mypage.test.ts.snap
- src/__tests__/auth/mypage.test.ts
- src/utils/Auth.ts
- tsconfig.json
[https://teamtuesday.atlassian.net/browse/SISO-136](https://teamtuesday.atlassian.net/browse/SISO-136)
(이슈링크 혹은 참조링크)
마이페이지 테스트 코드 추가
3/7(화)
> Feat: [SISO-136] mypage 테스트 코드 추가

- src/components/Vote/VoteHeader.svelte
- src/components/common/button/Button.svelte
- src/components/common/button/ButtonCancel.svelte
- src/components/common/button/ButtonOk.svelte
- src/components/common/confirm/Confirm.svelte
- src/components/common/menu/Menu.svelte
- tailwind.config.cjs
[https://teamtuesday.atlassian.net/browse/SISO-99](https://teamtuesday.atlassian.net/browse/SISO-99)
tailwind에 디자인 토큰 적용
3/7(화)
> Feat: [SISO-99] 디자인 토큰 개발
